// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGtpnbrtNEHbCwhxgiUF4MF4xOBC-x7qI',
    appId: '1:1067700216942:web:432645b585b74b5345b27f',
    messagingSenderId: '1067700216942',
    projectId: 'codeducation-27352',
    authDomain: 'codeducation-27352.firebaseapp.com',
    databaseURL: 'https://codeducation-27352-default-rtdb.firebaseio.com',
    storageBucket: 'codeducation-27352.firebasestorage.app',
    measurementId: 'G-LFK098L5R3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF8U27BrolQbdw3lifFZChXdllY2COZVk',
    appId: '1:1067700216942:android:273d9a32e168f0d045b27f',
    messagingSenderId: '1067700216942',
    projectId: 'codeducation-27352',
    databaseURL: 'https://codeducation-27352-default-rtdb.firebaseio.com',
    storageBucket: 'codeducation-27352.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw072yy5gVQTAIWzqwlsy_LOuO95KTQBc',
    appId: '1:1067700216942:ios:7622908f68da5cf245b27f',
    messagingSenderId: '1067700216942',
    projectId: 'codeducation-27352',
    databaseURL: 'https://codeducation-27352-default-rtdb.firebaseio.com',
    storageBucket: 'codeducation-27352.firebasestorage.app',
    iosClientId: '1067700216942-in2onpnrbl0id96rmb9ajkh0ej1ngi5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.codeducation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw072yy5gVQTAIWzqwlsy_LOuO95KTQBc',
    appId: '1:1067700216942:ios:7622908f68da5cf245b27f',
    messagingSenderId: '1067700216942',
    projectId: 'codeducation-27352',
    databaseURL: 'https://codeducation-27352-default-rtdb.firebaseio.com',
    storageBucket: 'codeducation-27352.firebasestorage.app',
    iosClientId: '1067700216942-in2onpnrbl0id96rmb9ajkh0ej1ngi5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.codeducation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGtpnbrtNEHbCwhxgiUF4MF4xOBC-x7qI',
    appId: '1:1067700216942:web:3c8bb34050c2d78845b27f',
    messagingSenderId: '1067700216942',
    projectId: 'codeducation-27352',
    authDomain: 'codeducation-27352.firebaseapp.com',
    databaseURL: 'https://codeducation-27352-default-rtdb.firebaseio.com',
    storageBucket: 'codeducation-27352.firebasestorage.app',
    measurementId: 'G-TCG4GLPZQW',
  );

}